services:
  - type: web
    name: borovy-frontend
    env: node
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NUXT_PUBLIC_API_BASE_URL
        value: https://borovy-backend4.vercel.app/api